spring:
  # config:
  #   import: "optional:configserver:http://localhost:8888"   # ❌ localhost will NOT work inside Docker
  # application:
  #   name: OrderService
  # profiles:
  #   active: dev

  config:
    import: "optional:configserver:http://configserver:8888"   # ✅ Use container name

  application:
    name: OrderService

  profiles:
    active: dev
